name: QA Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Python dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

    - name: flake8 Lint
      run: |
          flake8 --docstring-convention numpy --format=html --htmldir=test/results

    - name: Test with pytest
      run: |
          cd ..
          pytest --pyargs ${{ github.event.repository.name }} --html=${{ github.event.repository.name }}/test/results/${{ github.event.repository.name }}_test_results.html

    - name: 'Upload Artifact'
      if: always()
      uses: actions/upload-artifact@v3
      with:
          name: testlogs
          path: |
            test/results/**/*.*
            test/*.svg
          retention-days: 90
